/**: # wildcard for the node name
  ros__parameters:
    model:
      mass: 14.9 # rigid body mass
      inertia: [ 0.27, 0.265, 0.37 ]  # rigid body inertia
      #inertia: [ 0.15, 0.15, 0.2 ]  # rigid body inertia
      cog: [ 0.0, 0.0, 0.0 ]
      added_mass: [ 9.3, 14.2, 17.0, 0.11, 0.13, 0.27 ]
      #added_mass: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
      buoyancy: 14.31 #14.45  # equivalent mass for buoyancy (buoyancy force = buoyancy * -g)
      cob: [ 0.0, 0.0, 0.33 ] # [ 0.006, 0.0, 0.031 ]# center of buoyancy
      damping_linear: [ 9.5, 13.1, 15.0, 0.4, 0.3, 0.35 ]
      #damping_linear: [1.0, 1.0, 1.0, 0.3, 0.3, 0.3 ]
      damping_nonlinear: [ 38.4, 39.1, 80.7, 1.0, 1.2, 1.4 ]
      #damping_nonlinear: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

    manipulator_comp:

      # as the cob/cog and buoyancy are neutral for vehicle with added masses, subtract added mass and add mass for plate
        # 0.106 kg equivalent buoyancy mass for added weights
        # 1.15 kg mass for weights
        # 0.085 kg equivalent buoyancy mass for plate
        # 0.23 kg mass for plate
        # added compensation buoyancy_mass: mass_weights -buoyancy_weights - mass_plate + buoyancy_plate
        # origin: origin_weights * (mass_weights - buoyancy_weights) - origin_plate * (mass_plate - buoyancy_plate)
      origin:
        x: 0.096
        y: 0.05
        z: -0.113
      buoyancy_mass: 0.839 # must be equal to parameter in xacro file for BlueROV, buoyancy = relative_compensation